baseurl = "https://jsoss-sig.github.io/"
title = "OSSセキュリティ技術の会（Secure OSS SIG)"
languageCode = "ja-JP"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true

[taxonomies]
	category = "categories"
	tag = "tags"

[params]
	description = "Secure OSS SIG"
	author = "SOSS SIG"
    copyright = "SOSS SIG all rights reserved. 2016"

[[menu.main]]
    name = "会について(About us)"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/about/"
[[menu.main]]
    name = "Blog"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/post/"
[[menu.main]]
    name = "イベント等(Events)"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/event/"
[[menu.main]]
    name = "リンク(links)"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/links/"
